sudo: required
language: ruby
before_install:
- gem install bundler -v 1.13.7
script:
- bundle exec rake test
rvm:
- 2.4.0
deploy:
  provider: rubygems
  api_key:
    secure: "YsCfxfgSakp0pgAPQ0qVxFttVYCbb4eQa9Os7EGTZzNGW9TByB0jEUK+BMSxpaIfX7mvknleF3OsuhF/w4zoUd2HBzEtpZbNqEdFtws+KpyudgkX3A7qtRfantHs77HsahCGs0rDZ8W0BIA/KwB+biaFYGIZpz9VZwSQRCaBr//0tl8O41VYXnSVhk1rGVo6aI+3tSQN1iN9X3GArWTlBUbFVyxhxQxQzAeKvFduIh8s/Sb+mRNDVUCwR3TR817bESlrzx83JPLicVyCIIIIcwRI8CCf5cYeqJlp9//Q/Y43YwHbOr5ivhKTwSr8Mk8VCVXzrgEsCfbl3ZrJSQG1J5jptTNAFrQKQPRI0C5dFsHpLGijquuNskCfaouda4qtslcLWwCWBYT8wOHSWOmkD49xHEClFXcoFOCE+e/LxDV//89dh/R5fpeh009ja8Vjt7/QOzJU2fLZCDY6ASlBeTJ2s2gpwjwafr37XlymJRKM2zI3p8XdINN0TfvZG+jMsyyB3mFVkqYzFi2cpssjwpMZvwdBzDd1A4I/GNR6ME5YcFgi3p3ojtQBWNFXhNEtblyyGkM7F5I9l5i42yINceMwyi73H3VSjcx/gqGG6DSWoBGElDEqCQ7ycz7Nw1UA9wCEA3PkEm0QjAEXUXPLhFA+HAYMPKOf6Z8n7EvYHJg="
  on:
    tags: true
env:
  global:
    secure: "YsCfxfgSakp0pgAPQ0qVxFttVYCbb4eQa9Os7EGTZzNGW9TByB0jEUK+BMSxpaIfX7mvknleF3OsuhF/w4zoUd2HBzEtpZbNqEdFtws+KpyudgkX3A7qtRfantHs77HsahCGs0rDZ8W0BIA/KwB+biaFYGIZpz9VZwSQRCaBr//0tl8O41VYXnSVhk1rGVo6aI+3tSQN1iN9X3GArWTlBUbFVyxhxQxQzAeKvFduIh8s/Sb+mRNDVUCwR3TR817bESlrzx83JPLicVyCIIIIcwRI8CCf5cYeqJlp9//Q/Y43YwHbOr5ivhKTwSr8Mk8VCVXzrgEsCfbl3ZrJSQG1J5jptTNAFrQKQPRI0C5dFsHpLGijquuNskCfaouda4qtslcLWwCWBYT8wOHSWOmkD49xHEClFXcoFOCE+e/LxDV//89dh/R5fpeh009ja8Vjt7/QOzJU2fLZCDY6ASlBeTJ2s2gpwjwafr37XlymJRKM2zI3p8XdINN0TfvZG+jMsyyB3mFVkqYzFi2cpssjwpMZvwdBzDd1A4I/GNR6ME5YcFgi3p3ojtQBWNFXhNEtblyyGkM7F5I9l5i42yINceMwyi73H3VSjcx/gqGG6DSWoBGElDEqCQ7ycz7Nw1UA9wCEA3PkEm0QjAEXUXPLhFA+HAYMPKOf6Z8n7EvYHJg=" 
